[package]
name = "awaitchange"
version = "0.6.0"
authors = ["Nils Martel <nils.martel@graphmasters.net>"]
edition = "2018"
description = "CLI to perform actions on filechanges"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# get the last time a file or directory (including its contents) was updated
last-update-time = "0.1.1"
clap = { version = "4.6.1", features = ["derive"] }
